spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      host: localhost
      port: 6379

---

spring:
  config:
    activate:
      on-profile: docker
  data:
    redis:
      host: redis
      port: 6379

---

spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
