spring:
  config:
    activate:
      on-profile: test
  data:
    elasticsearch:
      host: localhost
      port: 9200

---
spring:
  config:
    activate:
      on-profile: docker
  elasticsearch:
    uris: http://elasticsearch:9200
    username: elasticsearch
    password: qwer1234!

