spring:
  config:
    activate:
      on-profile: test
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
---

spring:
  config:
    activate:
      on-profile: docker
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
    producer:
      bootstrap-servers: kafka:9092

