version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.listen-address=0.0.0.0:9090"
    volumes:
      - ./prometheus-prod.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - infra

  promtail:
    image: grafana/promtail
    container_name: promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail-prod.yml:/etc/promtail/promtail.yml
    command:
      - -config.file=/etc/promtail/promtail.yml
      - -config.expand-env=true
    env_file:
      - .env
    networks:
      - infra

volumes:
  prometheus_data:

networks:
  infra:
    name: infra