services:
  analysis-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: analysis-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      TZ: "Asia/Seoul"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

    networks:
      - infra

networks:
  infra:
    external: true
