services:
  analysis-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: analysis-service
    ports:
      - "8082:8082"
    extra_hosts:
      - "10.0.32.159:host-gateway"
      - "10.0.33.239:host-gateway"
      - "10.0.34.129:host-gateway"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      KAFKA_BOOTSTRAP_SERVERS: "10.0.32.159:19092,10.0.33.239:29092,10.0.34.129:39092"
      ES_HOST: https://1aef128f11714b44870402bd6190321d.ap-northeast-2.aws.elastic-cloud.com:443
      ES_USERNAME: elastic
      ES_PASSWORD: 81ieilMmNELN8Quf2Vq0Fv5y

      TZ: "Asia/Seoul"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

    networks:
      - infra

networks:
  infra:
    external: true
