services:
  auction-detail-parser:
    image: auction-detail-parser:latest
    container_name: auction-detail-parser
    env_file:
      - .env
    networks:
      - infra

  coupang-detail-parser:
    image: coupang-detail-parser:latest
    container_name: coupang-detail-parser
    env_file:
      - .env
    networks:
      - infra

  elevenst-detail-parser:
    image: elevenst-detail-parser:latest
    container_name: elevenst-detail-parser
    env_file:
      - .env
    networks:
      - infra

  gmarket-detail-parser:
    image: gmarket-detail-parser:latest
    container_name: gmarket-detail-parser
    env_file:
      - .env
    networks:
      - infra

networks:
  infra:
    external: true
