services:
  auction-url-parser:
    image: auction-url-parser:latest
    container_name: auction-url-parser
    env_file:
      - .env
    networks:
      - infra
    tmpfs:
      - /tmp:exec

  coupang-url-parser:
    image: coupang-url-parser:latest
    container_name: coupang-url-parser
    env_file:
      - .env
    networks:
      - infra
    tmpfs:
      - /tmp:exec

  elevenst-url-parser:
    image: elevenst-url-parser:latest
    container_name: elevenst-url-parser
    env_file:
      - .env
    networks:
      - infra
    tmpfs:
      - /tmp:exec

  gmarket-url-parser:
    image: gmarket-url-parser:latest
    container_name: gmarket-url-parser
    env_file:
      - .env
    networks:
      - infra
    tmpfs:
      - /tmp:exec

networks:
  infra:
    external: true
