plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.9-SNAPSHOT'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.sparta'
version = '0.0.1-SNAPSHOT'
description = 'product-service'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
	maven { url = 'https://repo.spring.io/snapshot' }
}

dependencies {
    //JPA
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    //Web
    implementation 'org.springframework.boot:spring-boot-starter-web'
    //Validation
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    //PostgresSQL
    runtimeOnly 'org.postgresql:postgresql'
    //actuator
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    //zipkin
    implementation 'org.springframework.cloud:spring-cloud-starter-sleuth'
    implementation 'org.springframework.cloud:spring-cloud-starter-zipkin:2.2.3.RELEASE'
    //prometheus
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'
    //lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    //init
	implementation 'org.springframework.boot:spring-boot-starter'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
