plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.9-SNAPSHOT'
    id 'io.spring.dependency-management' version '1.1.7'
}


group = 'com.sparta'
version = '0.0.1-SNAPSHOT'
description = 'recommend-service'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.spring.io/snapshot' }
}

dependencies {

    implementation 'org.springframework.boot:spring-boot-starter'

    // Web
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // JPA
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // Lombok
    implementation 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    // DevTools
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // PostgreSQL 드라이버
    runtimeOnly 'org.postgresql:postgresql'

    // JUnit Platform Launcher
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {

}

tasks.named('test') {
    useJUnitPlatform()
}
