spring:
  config:
    activate:
      on-profile: test
  kafka:
    consumer:
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      group-id: product
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
    producer:
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    listener:
      ack-mode: manual
      concurrency: 3
---

spring:
  config:
    activate:
      on-profile: local
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: product
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
      enable-auto-commit: false

    producer:
      bootstrap-servers: kafka:9092

    listener:
      ack-mode: manual
      concurrency: 3

---

spring:
  config:
    activate:
      on-profile: dev
  kafka:
    consumer:
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      group-id: product
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
      enable-auto-commit: false
    producer:
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

    listener:
      ack-mode: manual
      concurrency: 3