services:
  auction-review-parser:
    image: auction-review-parser:latest
    container_name: auction-review-parser
    env_file:
      - .env
    networks:
      - infra

  coupang-review-parser:
    image: coupang-review-parser:latest
    container_name: coupang-review-parser
    env_file:
      - .env
    networks:
      - infra

  elevenst-review-parser:
    image: elevenst-review-parser:latest
    container_name: elevenst-review-parser
    env_file:
      - .env
    networks:
      - infra

  gmarket-review-parser:
    image: gmarket-review-parser:latest
    container_name: gmarket-review-parser
    env_file:
      - .env
    networks:
      - infra

networks:
  infra:
    external: true
