spring:
  config:
    activate:
      on-profile: test

product-service:
  url: http://localhost:8080

---

spring:
  config:
    activate:
      on-profile: docker

product-service:
  url: http://product-service:8080
