spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?currentSchema=recommend_service_db
    username: postgres
    password: qwer1234!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        use_sql_comments: false
        database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace